// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shykjgojjrpovdvnzzwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoeWtqZ29qanJwb3Zkdm56endqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MjM1NTMsImV4cCI6MjA3NTQ5OTU1M30.vUtg5RSy3zVXgb1iIXTnkx-Bk5g3HS_SAGsnDjt4SVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});